pull_request_rules: 
  - name: Merge Queue
    conditions:
      - label=dependencies
    actions:
      queue:
        merge_method: rebase
        update_method: rebase
  - name: Continuously rebase dependencies pull requests 
    conditions:
      - label=dependencies
    actions:
      rebase:
queue_rules:
  - name: default 
    update_method: rebase
    merge_method: rebase
defaults:
  actions:
    queue:
      merge_method: rebase
      update_method: rebase
