pull_request_rules: 
  - name: Auto Merge
    conditions:
      - check-success=check-flake 
      - check-success=build-home-nix-system
      - check-success=build-home-nix-home
      - check-success=build-nixps-system
      - check-success=build-nixps-home
      - label=dependencies
    actions:
      merge:
        method: rebase
      