pull_request_rules:
  - name: Dispatch Checks Workflow
    conditions:
      - label=dependencies
    actions:
      github_actions:
        workflow:
          dispatch:
            - workflow: build.yml
              ref: ${{ github.head_ref }}
            - workflow: check.yml
              ref: ${{ github.head_ref }}
queue_rules:
  - name: default
    queue_conditions:
      - label=dependencies
    update_method: rebase
    merge_method: rebase
defaults:
  actions:
    queue:
      allow_merging_configuration_change: true
      merge_method: rebase
      update_method: rebase
