pull_request_rules:
  - name: Run Workflows
    conditions:
      - label=dependencies
    actions:
      github_actions:
        workflow:
          dispatch:
            - workflow: check-flake
  - name: Auto Merge
    conditions:
      - check-success=check-flake 
      - label=dependencies
    actions:
      merge:
        method: rebase
      