pull_request_rules: 
  - name: Merge Queue
    conditions:
      - label=dependencies
    actions:
      queue:
        merge_method: rebase
        update_method: rebase
queue_rules:
  - name: default
    queue_conditions:
      - label=dependencies
    update_method: rebase
    merge_method: rebase
defaults:
  actions:
    queue:
      allow_merging_configuration_change: true
      merge_method: rebase
      update_method: rebase
