#!/nix/store/51sszqz1d9kpx480scb1vllc00kxlx79-bash-5.2-p15/bin/bash
ignored=(/nix /dev /proc /etc)
ro_mounts=()
symlinks=()
etc_ignored=()
for i in /nix/store/i1b58kka2bhvwclvbnry0x4zh4smsy8s-steam-run-fhs/*; do
  path="/${i##*/}"
  if [[ $path == '/etc' ]]; then
    :
  elif [[ -L $i ]]; then
    symlinks+=(--symlink "$(/nix/store/c2bq8xsayc90s33fd5xbm1vh5lrmwcfq-coreutils-9.3/bin/readlink "$i")" "$path")
    ignored+=("$path")
  else
    ro_mounts+=(--ro-bind "$i" "$path")
    ignored+=("$path")
  fi
done

if [[ -d /nix/store/i1b58kka2bhvwclvbnry0x4zh4smsy8s-steam-run-fhs/etc ]]; then
  for i in /nix/store/i1b58kka2bhvwclvbnry0x4zh4smsy8s-steam-run-fhs/etc/*; do
    path="/${i##*/}"
    # NOTE: we're binding /etc/fonts and /etc/ssl/certs from the host so we
    # don't want to override it with a path from the FHS environment.
    if [[ $path == '/fonts' || $path == '/ssl' ]]; then
      continue
    fi
    ro_mounts+=(--ro-bind "$i" "/etc$path")
    etc_ignored+=("/etc$path")
  done
fi

for i in '/etc/static' '/etc/nix' '/etc/shells' '/etc/bashrc' '/etc/zshenv' '/etc/zshrc' '/etc/zinputrc' '/etc/zprofile' '/etc/passwd' '/etc/group' '/etc/shadow' '/etc/hosts' '/etc/resolv.conf' '/etc/nsswitch.conf' '/etc/profiles' '/etc/login.defs' '/etc/sudoers' '/etc/sudoers.d' '/etc/localtime' '/etc/zoneinfo' '/etc/machine-id' '/etc/os-release' '/etc/pam.d' '/etc/fonts' '/etc/alsa' '/etc/asound.conf' '/etc/ssl/certs' '/etc/ca-certificates' '/etc/pki'; do
  if [[ "${etc_ignored[@]}" =~ "$i" ]]; then
    continue
  fi
  if [[ -L $i ]]; then
    symlinks+=(--symlink "$(/nix/store/c2bq8xsayc90s33fd5xbm1vh5lrmwcfq-coreutils-9.3/bin/readlink "$i")" "$i")
  else
    ro_mounts+=(--ro-bind-try "$i" "$i")
  fi
done

declare -a auto_mounts
# loop through all directories in the root
for dir in /*; do
  # if it is a directory and it is not ignored
  if [[ -d "$dir" ]] && [[ ! "${ignored[@]}" =~ "$dir" ]]; then
    # add it to the mount list
    auto_mounts+=(--bind "$dir" "$dir")
  fi
done

declare -a x11_args
# Always mount a tmpfs on /tmp/.X11-unix
# Rationale: https://github.com/flatpak/flatpak/blob/be2de97e862e5ca223da40a895e54e7bf24dbfb9/common/flatpak-run.c#L277
x11_args+=(--tmpfs /tmp/.X11-unix)

# echo '--------------------'
# echo '$x11_args'
# echo ${x11_args[*]}

# echo '--------------------'
# echo '--------------------'
# Try to guess X socket path. This doesn't cover _everything_, but it covers some things.
if [[ "$DISPLAY" == :* ]]; then
  display_nr=${DISPLAY#?}
  local_socket=/tmp/.X11-unix/X$display_nr
  x11_args+=(--ro-bind-try "$local_socket" "$local_socket")
fi


cmd=(
  /nix/store/g6pq7lssrxlkqxk1fg1nwaj4fcv6pb1c-bubblewrap-0.8.0/bin/bwrap
  --dev-bind /dev /dev
  --proc /proc
  --chdir "$(pwd)"
  --unshare-user
  
  
  
  --unshare-uts
  --unshare-cgroup
  --die-with-parent
  --ro-bind /nix /nix
  # Our glibc will look for the cache in its own path in `/nix/store`.
  # As such, we need a cache to exist there, because pressure-vessel
  # depends on the existence of an ld cache. However, adding one
  # globally proved to be a bad idea (see #100655), the solution we
  # settled on being mounting one via bwrap.
  # Also, the cache needs to go to both 32 and 64 bit glibcs, for games
  # of both architectures to work.
  --tmpfs /nix/store/3n58xw4373jp0ljirf06d8077j15pc4j-glibc-2.37-8/etc \
  --symlink /etc/ld.so.conf /nix/store/3n58xw4373jp0ljirf06d8077j15pc4j-glibc-2.37-8/etc/ld.so.conf \
  --symlink /etc/ld.so.cache /nix/store/3n58xw4373jp0ljirf06d8077j15pc4j-glibc-2.37-8/etc/ld.so.cache \
  --ro-bind /nix/store/3n58xw4373jp0ljirf06d8077j15pc4j-glibc-2.37-8/etc/rpc /nix/store/3n58xw4373jp0ljirf06d8077j15pc4j-glibc-2.37-8/etc/rpc \
  --remount-ro /nix/store/3n58xw4373jp0ljirf06d8077j15pc4j-glibc-2.37-8/etc \
  --tmpfs /nix/store/hjdvz6w9qcqphw08hrxcarxc3y7xh8j4-glibc-2.37-8/etc \
  --symlink /etc/ld.so.conf /nix/store/hjdvz6w9qcqphw08hrxcarxc3y7xh8j4-glibc-2.37-8/etc/ld.so.conf \
  --symlink /etc/ld.so.cache /nix/store/hjdvz6w9qcqphw08hrxcarxc3y7xh8j4-glibc-2.37-8/etc/ld.so.cache \
  --ro-bind /nix/store/hjdvz6w9qcqphw08hrxcarxc3y7xh8j4-glibc-2.37-8/etc/rpc /nix/store/hjdvz6w9qcqphw08hrxcarxc3y7xh8j4-glibc-2.37-8/etc/rpc \
  --remount-ro /nix/store/hjdvz6w9qcqphw08hrxcarxc3y7xh8j4-glibc-2.37-8/etc \
  "${ro_mounts[@]}"
  "${symlinks[@]}"
  "${auto_mounts[@]}"
  # --tmpfs /tmp
  # "${x11_args[@]}"
  
  /nix/store/sdhirrani6470w8v3i6z9s337kkw2df4-steam-run-init "$@"
)

exec "${cmd[@]}"

