name: Build Flake

on:
  pull_request:
    branches-ignore:
      - "mergify/merge-queue/**"
  workflow_dispatch:

jobs:
  build-home-nix-system:
    uses: ./.github/workflows/prelude.yml
    secrets:
      GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    with:
      command: nix build .#nixosConfigurations.home-nix.config.system.build.toplevel --accept-flake-config
  build-home-nix-home:
    uses: ./.github/workflows/prelude.yml
    secrets:
      GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    with:
      command: nix build .#homeConfigurations.enikolov@home-nix.activationPackage --accept-flake-config
  build-nixps-system:
    uses: ./.github/workflows/prelude.yml
    secrets:
      GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    with:
      command: nix build .#nixosConfigurations.nixps.config.system.build.toplevel --accept-flake-config
  build-home-nixps-home:
    uses: ./.github/workflows/prelude.yml
    secrets:
      GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    with:
      command: nix build .#homeConfigurations.enikolov@nixps.activationPackage --accept-flake-config
