name: Cachix

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - .github/**
      - docs/**
      - .gitignore
      - README.md
      - LICENSE

jobs:
  cachix:
    runs-on: ubuntu-latest
    steps:
      - uses: easimon/maximize-build-space@v10
        with:
          overprovision-lvm: true
          remove-android: true
          remove-dotnet: true
          remove-haskell: true

      - uses: actions/checkout@v4
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          upstream-cache: https://e-nikolov-nix-config.cachix.org
      - uses: cachix/cachix-action@master
        with:
          name: e-nikolov-nix-config
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#homeConfigurations.enikolov@home-nix.activationPackage --accept-flake-config
      - run: nix build .#homeConfigurations.enikolov@nixps.activationPackage --accept-flake-config
      - run: nix build .#nixosConfigurations.home-nix.config.system.build.toplevel --accept-flake-config
      - run: nix build .#nixosConfigurations.nixps.config.system.build.toplevel --accept-flake-config
