name: "Check Flake"

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  check-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          fetch-depth: 0
      - uses: DeterminateSystems/flake-checker-action@v7
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
        # with:
        #   upstream-cache: https://e-nikolov-nix-config.cachix.org
      - run: nix run nixpkgs#alejandra -- -c .
      - run: nix flake check --accept-flake-config
