name: "Check Flake Inputs"

on:
  pull_request:
  push:
    branches: [master]

jobs:
  flake-checker:
    name: Flake checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v4
