#* Modified version of https://github.com/reckenrode/nixos-configs/blob/main/.github/workflows/main.yml

name: "Update flakes"

on:
  schedule:
    - cron: "0 * * * *"

  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@master
        with:
          name: e-nikolov-nix-config
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: DeterminateSystems/flake-checker-action@main
      - run: nix flake update
      - run: nix build .#homeConfigurations.enikolov@home-nix.activationPackage --accept-flake-config
      - run: nix build .#homeConfigurations.enikolov@nixps.activationPackage --accept-flake-config
      - run: nix build .#nixosConfigurations.home-nix.config.system.build.toplevel --accept-flake-config
      - run: nix build .#nixosConfigurations.nixps.config.system.build.toplevel --accept-flake-config
      - run: nix flake check
      - name: Update flake.lock
        # uses: DeterminateSystems/update-flake-lock@main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "flake.lock: Update"
          branch: master
          # commit_options: "--no-verify --signoff"
          commit_options: "--signoff"
          file_pattern: flake.lock
          commit_user_name: Flake Bot # defaults to "GitHub Actions"
          #commit_user_email: my-github-actions-bot@example.org # defaults to "actions@github.com"
          commit_author: Flake Bot <actions@github.com> # defaults to author of the commit that triggered the run
          skip_dirty_check: false
          skip_fetch: true
