name: Prelude

on:
  workflow_call:
    inputs:
      command:
        required: false
        type: string
      platform:
        default: "ubuntu"
        required: false
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  nix-setup:
    runs-on: "${{ inputs.platform }}-latest"
    steps:
      - uses: easimon/maximize-build-space@v10
        with:
          overprovision-lvm: true
          remove-android: true
          remove-dotnet: true
          remove-haskell: true
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          fetch-depth: 0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Nix Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
        # with:
        #   upstream-cache: https://e-nikolov-nix-config.cachix.org
      - name: "Run Input: ${{ inputs.command }}"
        run: "${{ inputs.command }}"
