#* Modified version of https://github.com/reckenrode/nixos-configs/blob/main/.github/workflows/main.yml

name: "Update flake.lock"

on:
  schedule:
    - cron: "0 * * * *"

  repository_dispatch:
  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update flake.lock"
          pr-labels: |
            dependencies
