#* Modified version of https://github.com/reckenrode/nixos-configs/blob/main/.github/workflows/main.yml

name: "Update flake.lock"

on:
  schedule:
    - cron: "0 * * * *"

  repository_dispatch:
  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-latest
    name: Update flake.lock

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update flake.lock" # Title of PR to be created
          pr-labels: | # Labels to be set on the PR
            dependencies
            automated
      # - name: Update flake.lock
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: "flake.lock: Update"
      #     branch: master
      #     # commit_options: "--no-verify --signoff"
      #     commit_options: "--signoff"
      #     file_pattern: flake.lock
      #     commit_user_name: Flake Bot # defaults to "GitHub Actions"
      #     #commit_user_email: my-github-actions-bot@example.org # defaults to "actions@github.com"
      #     commit_author: Flake Bot <actions@github.com> # defaults to author of the commit that triggered the run
      #     skip_dirty_check: false
      #     skip_fetch: true
