#* Modified version of https://github.com/reckenrode/nixos-configs/blob/main/.github/workflows/main.yml

name: "Update flake.lock"

on:
  schedule:
    - cron: "*/360 * * * *"

  repository_dispatch:
  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ steps.generate-token.outputs.token }}
          pr-title: "Update flake.lock"
          pr-labels: |
            dependencies
